FROM debian:buster-slim

RUN apt-get update
RUN apt-get install -y --no-install-recommends make build-essential libssl-dev  wget curl llvm 

RUN apt-get install -y git

ARG USER=docker
ARG UID=1000
ARG GID=1000
# default password for user
ARG PW=docker
# Using unencrypted password/ specifying password
RUN useradd --no-log-init -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | \
      chpasswd

# Setup default user, when enter docker container
USER ${UID}:${GID}

WORKDIR /home/${USER}

ENV HOME="/home/$USER"

RUN git clone --depth=1 https://github.com/pyenv/pyenv.git .pyenv
ENV PYENV_ROOT="${HOME}/.pyenv"
ENV PATH="${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"

ENV PYTHON_VERSION=miniconda3-4.7.12
RUN pyenv install ${PYTHON_VERSION}
RUN pyenv global ${PYTHON_VERSION}
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -


COPY --chown=$USER:$USER poetry.lock pyproject.toml ./
RUN /bin/bash -c 'source $HOME/.poetry/env && POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-dev --no-root'

COPY . .
ENTRYPOINT [ "/bin/bash" ]
#ENTRYPOINT [ "/bin/bash", "-c", "source $HOME/.poetry/env && poetry run python AGRN.py" ]

