#Debug mode
debug	0
#ESpritz path
ESpritz	/home/nmalhis/Espritz/
#input fasta file
Input	input.fasta
#output file
Output	output.txt   
# UniProt Swiss-Prot database (source: http://www.uniprot.org/downloads)
SwissProt	/data/database/DB/SP/SP
# UniProt UniRef90 database (source: http://www.uniprot.org/downloads)
UniRef90	/data/database/DB/uniref90filt/uniref90filt
# number of threads
threads	8
